3. Flask_Complete_Website/project/arts/routes.py
from flask import render_template ,request, Blueprint
from project.arts import ascii_art

arts = Blueprint('arts', __name__)

# First Section
@arts.route('/printRect', methods=['GET','POST'])
def printRect():
    user = {'message': 'welcome to ASCII arts page!'}
    if request.method =='POST':
        width = request.form['width']
        height = request.form['height']
        symbol = request.form['symbol']
        output = ascii_art.printRect(width,height,symbol)
        # print(output)
        return render_template('ASCII_Results.html', title='ASCII Result', output=output)
    return render_template('ASCII_Art.html', title='ASCII arts', user=user)

# Section Section
@arts.route('/printTriangle', methods=['POST'])
def printTriangle():

    if request.method =='POST':
        width = request.form['width']
        symbol = request.form['symbol']
        whichsideup = request.form['whichsideup']
        output = ascii_art.printTriangle(width,symbol,whichsideup)
        # print(output)
        return render_template('ASCII_Results.html', title='ASCII Result', output=output)


# Third Section
@arts.route('/printBumps', methods=['POST'])
def printBumps():

    if request.method =='POST':
        number = request.form['number']
        symbol1 = request.form['symbol1']
        symbol2 = request.form['symbol2']
        output = ascii_art.printBumps(number, symbol1, symbol2)
        return render_template('ASCII_Results.html', title='ASCII Result', output=output)



# Fourth Section
@arts.route('/printDiamond', methods=['POST'])
def printDiamond():

    if request.method =='POST':
        width = request.form['number']
        symbol = request.form['symbol']
        output = ascii_art.printDiamond(width, symbol)
        return render_template('ASCII_Results.html', title='ASCII Result', output=output)


# Fifth Section
@arts.route('/printStripedDiamond', methods=['POST'])
def printStripedDiamond():

    if request.method =='POST':
        width = request.form['number']
        symbol1 = request.form['symbol1']
        symbol2 = request.form['symbol2']
        output = ascii_art.printStripedDiamond(width, symbol1,symbol2)
        return render_template('ASCII_Results.html', title='ASCII Result', output=output)



# Sixth Section
@arts.route('/printCrazyStripedDiamond', methods=['POST'])
def printCrazyStripedDiamond():

    if request.method =='POST':
        width = request.form['number']
        symbol1 = request.form['symbol1']
        symbol2 = request.form['symbol2']
        sym1Width = request.form['sym1Width']
        sym2Width = request.form['sym2Width']
        output = ascii_art.printCrazyStripedDiamond(width, symbol1, symbol2, sym1Width, sym2Width)
        return render_template('ASCII_Results.html', title='ASCII Result', output=output)

# Seventh Section
@arts.route('/printStarTree', methods=['POST'])
def printStarTree():

    if request.method =='POST':
        width = request.form['number']
        symbol1 = request.form['symbol']
        output = ascii_art.printStarTree(width, symbol1)
        return render_template('ASCII_Results.html', title='ASCII Result', output=output)


# Eighth Section
@arts.route('/printLuxuryTree', methods=['POST'])

def printLuxuryTree():
    
    if request.method =='POST':
        width = request.form['number']
        symbol1 = request.form['symbol1']
        symbol2 = request.form['symbol2']
        output = ascii_art.printLuxuryTree(width, symbol1, symbol2)
        return render_template('ASCII_Results.html', title='ASCII Result', output=output)

3. Flask_Complete_Website/project/sleepwalk/routes.py
from flask import render_template, request, Blueprint
from project.sleepwalk import sleep

sleepwalk = Blueprint('sleepwalk', __name__)

@sleepwalk.route('/sleepwalk', methods = ['GET','POST'])
def sleep_walk():
    user = {'message': 'welcome to Sleep Walking Student page!'}
    if request.method == 'POST':
        start = request.form['start']
        low = request.form['low']
        high = request.form['high']
        output = sleep.rwsteps(start, low, high)
        # print(output)
        return render_template('sleepwalk_Results.html', title='Sleep Walk Student', output=output)
    return render_template('sleepwalk.html', title='Sleep Walk', user=user)

3. Flask_Complete_Website/project/steg/routes.py
from flask import Flask, render_template ,request, Blueprint, flash,redirect,send_from_directory
from werkzeug import secure_filename
import os
import PIL
from PIL import Image
import PIL.ImageOps
from project import project
import cv2 as cv
from project.steg import desteg


UPLOAD__IMAGE_FOLDER = '..'

steg = Blueprint('steg', __name__)

Image_Folder= os.path.dirname(os.path.abspath(__file__))+'/images'

# Used for uploading pictures
@steg.route('/<filename>')
def get_file(filename):
    return send_from_directory(Image_Folder,filename)


# invert images
@steg.route('/image', methods=['GET', 'POST'])
def invert_file():
    if request.method == 'POST':
        # check if the post request has the file part
        if 'file' not in request.files:
            flash('No file part')
            return redirect(request.url)
        file = request.files['file']
        # If user does not select file, browser also
        # submit an empty part without filename
        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)
        # if the image is valid, do the following
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            # Create a path to the image in the upload folder, save the upload
            # file to this path
            save_old=(os.path.join(Image_Folder, filename))
            file.save(save_old)
            # print('this is:', save_old)
            # Take the image, make a new one that is inverted
            img = Image.open(save_old)
            rbg_img = img.convert('RGB')
            inverted_image = PIL.ImageOps.invert(rbg_img)

            save_new=(os.path.join(Image_Folder, 'new_'+filename))
            inverted_image.save(save_new)
            # Render template with inverted picture
            # rt = render_template('imageResults.html', filename='new_'+filename)
            # print('this is new_'+filename)
            return render_template('image_Results.html', title = 'Covert RGB Result!',filename='new_'+filename)
    return render_template('image.html', Title = 'Convert RGB')


# Steg image
#  /steg  This is for html path
@steg.route('/steg', methods=['GET', 'POST'])
# function name is for the action in html.
def steg_file():
    if request.method == 'POST':
        # check if the post request has the file part
        if 'file' not in request.files:
            flash('No file part')
            return redirect(request.url)
        file = request.files['file']
        # If user does not select file, browser also
        # submit an empty part without filename
        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)
        # if the image is valid, do the following
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            # Create a path to the image in the upload folder, save the upload
            # file to this path
            save_old=(os.path.join(Image_Folder, filename))
            file.save(save_old)
            # print('this is:', save_old)
            # read the image by using opencv
            # img = cv.imread(save_old, cv.IMREAD_COLOR)
            # send it to the function store in desteg file then return the result.
            message = request.form['inputtext']
            # print(message)
            msg2 = desteg.steg_message(save_old,message)
            filename = msg2
            # save_new = (os.path.join(project.config['UPLOAD__IMAGE_FOLDER'], 'new_' + filename)) -> ? how do i make this work
            # so i can return a image path to html and show it in HTML
            # print(filename2)
            return render_template('steg_Results.html', title = 'Steg Result', filename = filename)


# desteg images
@steg.route('/desteg', methods=['GET', 'POST'])
def desteg_file():
    if request.method == 'POST':
        # check if the post request has the file part
        if 'file' not in request.files:
            flash('No file part')
            return redirect(request.url)
        file = request.files['file']
        # If user does not select file, browser also
        # submit an empty part without filename
        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)
        # if the image is valid, do the following
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            # Create a path to the image in the upload folder, save the upload
            # file to this path
            save_old=(os.path.join(Image_Folder, filename))
            file.save(save_old)
            # print('this is:', save_old)
            # read the image by using opencv
            # img = cv.imread(save_old, cv.IMREAD_COLOR)
            # send it to the function store in desteg file then return the result.
            msg2 = desteg.desteg(save_old)

            return render_template('desteg_Results.html', title = 'Desteg Result', msg2=msg2)
    return render_template('desteg.html', title = 'Desteg the Images!!')





'''If there are multiple upload folder,s extensions cound't be the same'''
# allowed file types
IMAGE_EXTENSIONS = {'png','jpg','jpeg'}
project.config['IMAGE_EXTENSIONS']=IMAGE_EXTENSIONS

# is file allowed to be uploaded?
def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1] in project.config['IMAGE_EXTENSIONS']

3. Flask_Complete_Website/project/templates/ASCII_Art.html
{% extends "base.html" %} {% block content %}
<!-- <h1>Hi, {{ user.message }}!</h1> -->
<head>
  <link
    rel="stylesheet"
    href="{{ url_for('static', filename='css/ascii.css') }}"
  />
  <!-- <link rel="stylesheet" href="../static/css/ascii.css"/> -->
</head>

<body>
  <h2>Welcome to the ASCII World!!!!</h2>
  <div class="des">
    ASCII abbreviated from American Standard Code for Information Interchange,
    is a character encoding standard for electronic communication. Find on more
    here: <a href="https://en.wikipedia.org/wiki/ASCII"> on Wikipedia</a> <br />
    There are six python functions that allow you to create some shapes by using
    ASCII characters. This is just an example, if you don't like these shapes,
    you can write your own python function to create your own ASCII art work,
    ENJOY!
  </div>

  <div class="nav-bar">
    <ul class="nav">
      <li><a href="#one">Rectangular</a></li>
      <li><a href="#two">Triangle</a></li>
      <li><a href="#three">Bumps</a></li>
      <li><a href="#four">Diamond</a></li>
      <li><a href="#five">Striped Diamond</a></li>
      <li><a href="#six">Crazy Striped Diamond</a></li>
      <li><a href="#seven">Basic Christmas Tree</a></li>
      <li><a href="#eight">Luxury Christmas Tree</a></li>
    </ul>
  </div>

  {# section 1#}
  <div class="display-right">
    <div id="one" class="section">
      <p>Print Rectangular</p>
      <form action="{{ url_for('arts.printRect') }}" method="post">
        Input Width:
        <input type="text" name="width" /><br /><br />
        Input Height:
        <input type="text" name="height" /><br /><br />
        Input Symbol:
        <input type="text" name="symbol" /><br /><br />
        <input type="submit" value="Submit" /><br />
      </form>
    </div>

    {# section 2#}
    <div id="two" class="section">
      <p>Print Triangle</p>
      <form action="{{ url_for('arts.printTriangle') }}" method="post">
        Input Width:
        <input type="text" name="width" /><br /><br />
        Input Symbol:
        <input type="text" name="symbol" /><br /><br />
        Input True of False:
        <input type="text" name="whichsideup" /><br /><br />
        <input type="submit" value="Submit" /><br />
      </form>
    </div>

    {# section 3#}
    <div id="three" class="section">
      <p>Print Bumps</p>
      <form action="{{ url_for('arts.printBumps') }}" method="post">
        Input Number:
        <input type="text" name="number" /><br /><br />
        Input Symbol 1:
        <input type="text" name="symbol1" /><br /><br />
        Input Symbol 2:
        <input type="text" name="symbol2" /><br /><br />
        <input type="submit" value="Submit" /><br />
      </form>
    </div>

    {# section 4#}
    <div id="four" class="section">
      <p>Print Diamond</p>
      <form action="{{ url_for('arts.printDiamond') }}" method="post">
        Input Width:
        <input type="text" name="number" /><br /><br />
        Input Symbol :
        <input type="text" name="symbol" /><br /><br />
        <input type="submit" value="Submit" /><br />
      </form>
    </div>

    {# section 5#}
    <div id="five" class="section">
      <p>Print Striped Diamond</p>
      <form action="{{ url_for('arts.printStripedDiamond') }}" method="post">
        NOTE: Try Width 7 or above. It's easier to see.<br /><br />
        Input Width:
        <input type="text" name="number" /><br /><br />
        Input Symbol 1:
        <input type="text" name="symbol1" /><br /><br />
        Input Symbol 2:
        <input type="text" name="symbol2" /><br /><br />
        <input type="submit" value="Submit" /><br />
      </form>
    </div>

    {# section 6#}
    <div id="six" class="section">
      <p>Print Crazy Striped Diamond</p>
      <form
        action="{{ url_for('arts.printCrazyStripedDiamond') }}"
        method="post"
      >
        NOTE: Width > Sym1 Width > Sym2 Width <br /><br />
        Input Width:
        <input type="text" name="number" /><br /><br />
        Input Symbol 1:
        <input type="text" name="symbol1" /><br /><br />
        Input Symbol 2:
        <input type="text" name="symbol2" /><br /><br />
        Input Symbol 1 Width:
        <input type="text" name="sym1Width" /><br /><br />
        Input Symbol 2 Width:
        <input type="text" name="sym2Width" /><br /><br />
        <input type="submit" value="Submit" /><br />
      </form>
    </div>

    {# section 7#}
    <div id="seven" class="section">
      <p>Print Basic Christmas Tree</p>
      <form action="{{ url_for('arts.printStarTree') }}" method="post">
        Input Height:
        <input type="text" name="number" /><br /><br />
        Input Symbol:
        <input type="text" name="symbol" /><br /><br />
        <input type="submit" value="Submit" /><br />
      </form>
    </div>

    {# section 8#}
    <div id="eight" class="section">
      <p>Print Luxury Christmas Tree</p>
      <form action="{{ url_for('arts.printLuxuryTree') }}" method="post">
        NOTE: Height should be an odd number and greater than 3. Suggested using
        number greater than 5!!<br /><br />
        Input Height:
        <input type="text" name="number" /><br /><br />
        Input Symbol1:
        <input type="text" name="symbol1" /><br /><br />
        Input Symbol2:
        <input type="text" name="symbol2" /><br /><br />
        <input type="submit" value="Submit" /><br />
      </form>
    </div>
  </div>
</body>
{% endblock %}

3. Flask_Complete_Website/project/templates/ASCII_Results.html
{% extends "base.html" %}
{##jinja2: lstrip_blocks: False#}
{##jinja2: trim_blocks: False#}

{% block content %}
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/ascii_result.css') }}" />
    <!-- <link rel="stylesheet" href="../static/css/ascii.css"/> -->
</head>
<body>
    <h2>Output:</h2>
    <pre section="result">
    {# This has to be one line because if you format the code, <pre> will print out the enter  #}
     {% for line in output -%} <div style="font-size:150%">{{ line.line }}</div>{% endfor -%}
    </pre>
</body>
{% endblock %}

3. Flask_Complete_Website/project/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Flask App Project</title>
    <!-- <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}" /> -->
    <link rel="stylesheet" href="../static/css/base.css" />

</head>

<body>
    <header>
        <h1>Welcome To Flask App Project For IST341 </h1>
        <nav>
            <a href="/index">Home</a>
            <a href="/printRect">ASCII Art</a>
            <a href="/desteg">Steganography</a>
            <a href="/image">Convert Image</a>
            <a href="/countalpha">Count Letters</a>
        </nav>
    </header>

    {% block content %}{% endblock %}
</body>

</html>

3. Flask_Complete_Website/project/templates/complete.html
{% extends "base.html" %}

{% block content %}
<head>
    <title>Title</title>
</head>


<body>file uploaded</body>



{% endblock %}

3. Flask_Complete_Website/project/templates/countalpha.html
{% extends "base.html" %}

{% block content %}
 <!doctype html>
{#    <title>Steganography</title>#}
<head>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/count.css') }}" />
  <link rel="stylesheet" href="../static/css/count.css"/>
</head>

<body>
    <h2>Count Alphabet </h2>
    <div class=des>
      This is a simple program counting how many times each alphabet appears in a text document. The program will not count punctuation marks.
    </div>


    
    <p>Upload Text File</p>
    <form  method=post enctype=multipart/form-data>
      <input type=file name=file>
      <input type=submit value=Upload>
    </form>
</body>
{% endblock %}

3. Flask_Complete_Website/project/templates/countalpha_Results.html
{% extends "base.html" %}


{% block content %}

<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/countresult.css') }}" />
    <!-- <link rel="stylesheet" href="../static/css/ascii.css"/> -->
</head>
<body>
    <h2>Output:</h2>
    <pre>
    {# This has to be one line because if you format the code, <pre> will print out the enter  #}
        {% for line in output -%} <div style="font-size:150%">{{ line.line }}</div>{% endfor -%}
    </pre>
</body>
{% endblock %}

3. Flask_Complete_Website/project/templates/desteg.html
{% extends "base.html" %}

{% block content %}
 <!doctype html>
 <head>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/desteg.css') }}" />
    <!-- <link rel="stylesheet" href="../static/css/desteg.css"/> -->
</head>
<body>
    <h2> Do you know what is Steganography?</h2>
    <div class=des>
        Steganography allows you to encrypt and decrypt message in a image. There are two functions for you to play with on this page. First, when you choose the Steg image, please select one image that is <b>PNG</b> format. The reason it has to be png not jpg because jpg is a compressed image, the program will not work. Once you chose a png image, the next step is enter a message. Then, click upload it will return a image with message encrypted. <br>

        When you finish encrypting the image, you can download it and then use the Desteg image function to decrypt it. Amazing right? Find out more about Steganography here: <a href="https://en.wikipedia.org/wiki/Steganography">on Wikipedia</a>
    </div>


    <div class="nav-bar">
        <ul class="nav">
            <li><a href=#one>Steg Image</a></li>
            <li><a href=#two>Desteg Image</a></li>
        </ul>
    </div>   


    <div class = display-right>
        <div id=one class=section >
            {#    action="{{ url_for('steg.steg_file') }} this is the function name not the one start with / in routes#}
            <p>Steg Image</p>
            Only <b>PNG</b> files are allowed!!!<br>
            <form  action="{{ url_for('steg.steg_file') }}" method=post enctype=multipart/form-data>
        
                select a file:
                <input type=file name=file>
                Input message:
                <input type=text name=inputtext>
                <input type=submit value=Upload>
            </form>
        </div>

        <div id=two class=section>
            <p>Desteg Image</p>
            <form action="{{ url_for('steg.desteg_file') }}" method=post enctype=multipart/form-data>
                select a file:
                <input type=file name=file>
                <input type=submit value=Upload>
            </form>
        </div>
    </div>

</body>
    {% endblock %}

3. Flask_Complete_Website/project/templates/desteg_Results.html
{% extends "base.html" %}

{% block content %}    
<!doctype html>
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/desteg_result.css') }}" />
    <!-- <link rel="stylesheet" href="../static/css/desteg_result.css"/> -->
</head>
<body>
    <h2>Decrypted Result</h2>
    <p>Here is the message hidden in the picture: <b>{{ msg2 }}</b></p>
</body>
{% endblock %}

3. Flask_Complete_Website/project/templates/image.html
{% extends "base.html" %}

{% block content %}
 <!doctype html>

 <head>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/image.css') }}" />
  <!-- <link rel="stylesheet" href="../static/css/image.css"/> -->
</head>

<body>

  <h2> Image Converter</h2>
  <div class=des>
      You know a color is a combination of Red, Green and Blue. But, do you know what will happen if you make RGB to GBR or other orders? <br> Find out by using the function below! 

  </div>
  <div class = display-right>
    <div id=one class=section >
      <p> Invert RGB </p>
      <form method=post enctype=multipart/form-data>
        <input type=file name=file>
        <input type=submit value=Upload>
      </form>
  </div>  
</body>
{% endblock %}

3. Flask_Complete_Website/project/templates/image_Results.html
{% extends "base.html" %}

{% block content %}    
<!doctype html>
<head>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/image_result.css') }}" />
  <link rel="stylesheet" href="../static/css/image_result.css"/>
</head>
<body>
  <h2>Your Inverted Image!</h2>
  {% if filename %}
    <p>Here is the Inverted Image</p>
    <img src="{{url_for('steg.get_file', filename=filename) }}">
  {% endif %}
</body> 

  
{% endblock %}

3. Flask_Complete_Website/project/templates/index.html
{% extends "base.html" %}

{% block content %}

<head>
    <!-- <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}" /> -->
    <link rel="stylesheet" href="../static/css/index.css" />
</head>


<!-- <h1>Hi, {{ user.message }}!</h1> -->

<body>
    <section>
        <h2>Description</h2>
        <p>Welcome to the Flask App project. In this project, you will Flask to build a web application. You are going
            to use Python as the main programming language. In addition, you may also need write some HTML code for your
            website. If you give your website a little bit design or color, CSS and JavaScript are also welcome. Feel
            free to ask questions and enjoy your web development with Flask and Python. </p>
    </section>
    <section>
        <h2>Skills</h2>

        <table>
            <tr>
                <th>Mandatory</th>
                <th>Optional</th>
            </tr>

            <tr>
                <ul>
                    <td>
                        <li><span>Flask</span></li>
                        <li><span>Python</span></li>
                        <li><span>HTML</span></li>
                    </td>

                    <td>
                        <li><span>Git</span></li>
                        <li><span>CSS</span></li>
                        <li><span>JavaScript</span></li>
                    </td>
                </ul>
            </tr>
        </table>

    </section>
    <section>
        <h2>Resource</h2>
        <h4>Here are some useful resources you can learn more about Flask</h4>
        <p>I have created a sample project that you can start with, please visit the GitHub repository at <a href="https://github.com/cct823/IST341_Flask_Demo">IST341 Sample Project</a><p>
        <p><a href="https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world"> Flask Tutorial</a> -- This website provides a really good Flask tutorial, you only need first two chapters to have the basic knowledge to complete this project.</li>
        </p>
        <p>If you want to put different functions in different folders, you may want to search <b>Blueprints</b></p>
        <p>If you want to make your website colorful, you can use <b>CSS or JavaScript</b></p>
    </section>
</body>

{% endblock %}

3. Flask_Complete_Website/project/templates/sleepwalk.html
{% extends "base.html" %}

{% block content %}
    <h1>Hi, {{ user.message }}!</h1>
    <div> Below are few functions that allows you to play with the Sleep Walk Students</div>

    {#    section 1#}
    <p style="font-size:150%"> Enter Start, Low, High Positions </p>
    <form  method="post">
        Input Start:
        <input type=text  name=start ><br><br>
        Input Low:
        <input type=text  name=low ><br><br>
        Input High:
        <input type=text    name=high ><br><br>
        <input type=submit  value=Submit><br>
    </form>

{% endblock %}

3. Flask_Complete_Website/project/templates/sleepwalk_Results.html
{% extends "base.html" %}


{% block content %}

    <h1>Output:</h1>
    <pre>
    {# This has to be one line because if you format the code, <pre> will print out the enter  #}
     {% for line in output -%} <div style="font-size:150%">{{ line.line }}</div>{% endfor -%}
    </pre>
{% endblock %}

3. Flask_Complete_Website/project/templates/steg_Results.html
{% extends "base.html" %}

{% block content %}
<!doctype html>
<head>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/desteg_result.css') }}" />
  <!-- <link rel="stylesheet" href="../static/css/desteg_result.css"/> -->
</head>
<body>
  <h2>Steg Image Result</h2>
  
  {% if filename %}
    <p>Here is the file name of the image below <b>{{ filename }}</b></p>
    <p>Now, download this image and try to use the Desteg function!!!</p>
    <img src="{{url_for('steg.get_file', filename=filename) }}">
  {% endif %}
</body> 
{% endblock %}